### ISSUE TITLE
Pod 安装报错！ 项目用的swift 

### ISSUE THREAD

**Issue by z234009184** [cdnbye/ios-p2p-engine#2]
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/apple/Desktop/demo/ios/Pods/CDNByeSDK/CDNByeSDK/CDNByeKit.framework)

可以不可以在podspec加上
s.static_framework = true

**Comment by snowinszu** [comment]
好的，感谢您的建议，方便的话请QQ联系我们具体沟通：849433499

**Comment by snowinszu** [comment]
最新版1.8.1已经增加 s.static_framework = true
