### ISSUE TITLE
1 duplicate symbol for architecture arm64

### ISSUE THREAD

**Issue by ZJF-Coder** [cdnbye/ios-p2p-engine#3]
你好，我下载你们的demo，pod install完了运行没问题，但是同样在公司项目中引入你们的sdk时，和其他第三方sdk冲突报错了，不知道是要怎么解决好点，下面贴上我们的报错信息：

duplicate symbol '_USER_AGENT' in:
    /Users/jy/Library/Developer/Xcode/DerivedData/VideoWatcher-aycxlpxesblljwavaydrksjyfjtk/Build/Products/Debug-iphoneos/SwarmCloudSDK.framework/SwarmCloudSDK(SWCTracker.o)

/Users/jy/Desktop/WTVideo/VideoWatcher/Foundation/Packages/YTXOperators.framework/YTXOperators(UAHTTPOperation.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

YTXOperators这个第三方我们业务需要用到，因此不能去掉，请问有什么好的方式解决吗？

**Comment by snowinszu** [comment]
你好，这个错误是因为有些静态变量没有加前缀，跟别的库重名了，我们目前正在修复，方便的话加客服QQ：849433499

**Comment by ZJF-Coder** [comment]
你好，已发送好友申请，麻烦通过
